IMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('inventory.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),

    # For Login 
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logoutUser/',views.logoutUser,name='logoutUser'),
    path('profile/',views.profile,name='profile'),
    path('change_password/',views.change_password,name='change_password'),

]

inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("add_amount/", views.add_amount, name="add_amount"),
    path("add_transaction/", views.add_transaction, name="add_transaction"),
    path("view_credit/", views.view_credit, name="view_credit"),
    path("view_debit/", views.view_debit, name="view_debit"),
    path(
        "view_all_transaction/", views.view_all_transaction, name="view_all_transaction"
    ),
    # For Employee
    path("employee/", views.employee, name="employee"),
    path("add_employee/", views.add_employee, name="add_employee"),
    path("<int:emp_id>/emp_edit/", views.emp_edit, name="emp_edit"),
    path(
        "<int:emp_id>/delete_employee/", views.delete_employee, name="delete_employee"
    ),
    path("<int:emp_id>/view_works/", views.view_works, name="view_works"),
    path("<int:emp_id>/add_work/", views.add_work, name="add_work"),
    # For Salary
    path("<int:emp_id>/pay_now/", views.pay_now, name="pay_now"),
    path("salary_cal/", views.salary_cal, name="salary_cal"),
    path("pay_all/", views.pay_all, name="pay_all"),
    path("<int:emp_id>/salary_details/", views.salary_details, name="salary_details"),
    # For Customer
    path("customer/", views.customer, name="customer"),
    path("add_customer/", views.add_customer, name="add_customer"),
    path("<int:cus_id>/cust_edit/", views.cust_edit, name="cust_edit"),
    path(
        "<int:cus_id>/delete_customer/", views.delete_customer, name="delete_customer"
    ),
    # For orders
    path("order_all/", views.order_all, name="order_all"),
    path("order_not_delivered/", views.order_not_delivered, name="order_not_delivered"),
    path("order_delivered/", views.order_delivered, name="order_delivered"),
    path("<int:cus_id>/order_list/", views.order_list, name="order_list"),
    path("<int:cus_id>/order_now/", views.order_now, name="order_now"),
    path("<int:ord_id>/order_details/", views.order_details, name="order_details"),
    path("<int:ord_id>/delivered/", views.delivered, name="delivered"),
    # path('<int:ord_id>/download_order/', views.download_order, name='download_order'),
    # For product
    path("product_details/", views.product_details, name="product_details"),
    path("add_product/", views.add_product, name="add_product"),
    path("<int:pro_id>/edit_product/", views.edit_product, name="edit_product"),
    path("<int:pro_id>/delete_product/", views.delete_product, name="delete_product"),
    # For Supplier
    path("supplier/", views.supplier, name="supplier"),
    path("add_supplier/", views.add_supplier, name="add_supplier"),
    path("<int:sup_id>/sup_edit/", views.sup_edit, name="sup_edit"),
    path(
        "<int:sup_id>/delete_supplier/", views.delete_supplier, name="delete_supplier"
    ),
    # For Raw Materials
    path("materials/", views.materials, name="materials"),
    path("add_material/", views.add_material, name="add_material"),
    path("<int:mat_id>/material_edit/", views.material_edit, name="material_edit"),
    path(
        "<int:mat_id>/delete_material/", views.delete_material, name="delete_material"
    ),
    path("view_purchase/", views.view_purchase, name="view_purchase"),
    path("buy_material/", views.buy_material, name="buy_material"),
   #  员工考勤
    path("attendance/", views.attendance, name="attendance"),
    path("facerec/", views.facerec, name="facerec"),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm

class UserForm(UserChangeForm):
	class Meta:
		model=User
		fields=['email','first_name','last_name']
		labels={
		   'last_name':'手机号码',
		   'first_name':'组织名称'
		}
		widgets={
		'email':forms.TextInput(attrs={'class':'form-control',}),
		'first_name':forms.TextInput(attrs={'class':'form-control',}),
		'last_name':forms.TextInput(attrs={'class':'form-control'}),
		}

class PasswordForm(PasswordChangeForm):
	class Meta:
		model=User
		fields=['old_password','new_password','new_password_confirmation']
		labels={
		   'old_password':'旧密码',
		   'new_password':'新密码',
		   'new_password_confirmation':'确认新密码'
		}
		
		widgets={
		'old_password':forms.TextInput(attrs={'class':'form-control','placeholder':'输入旧密码'}),
		'new_password':forms.TextInput(attrs={'class':'form-control','placeholder':'输入新密码'}),
		'new_password_confirmation':forms.TextInput(attrs={'class':'form-control','placeholder':'再次输入新密码'})
		}

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.models import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from tenants.models import Client, Domain
from inventory.models import Accounts
import re 
from django.shortcuts import get_object_or_404
from django.db import connection
from django_tenants.utils import schema_context
from .forms import *

# Create your views here.
def index(request):
	return render(request, 'index.html')

def register(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		name 	 = request.POST['name']
		email 	 = request.POST['email']
		phno 	 = request.POST['phno'] # Storing phno in last_name

		
		# Function checks if the string contains any special character 
		regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')

		if(regex.search(username) != None):
			messages.error(request,'用户名不能包含任何特殊名称')
			messages.info(request,'试试其他的用户名')
			return redirect('home:register')

		if bool(re.search(r"\s", username))  == True :
			messages.error(request,'用户名不能包含空格')
			messages.info(request,'试试其他的用户名')
			return redirect('home:register')

		if username.islower() != True :
			messages.error(request,'用户名必须是小写的')
			messages.info(request,'试试其他的用户名')
			return redirect('home:register')

		if User.objects.filter(username=username).exists() :
			messages.error(request,'用户名已被占用')
			messages.info(request,'试试其他的用户名')
			return redirect('home:register')

		user = User.objects.create_user(username=username, password=password, first_name=name, last_name=phno, email=email)
		user.save() 

		tenant = Client.objects.create(user=user, schema_name= user.username)
		tenant.save()
		domain = Domain()
		domain.domain = tenant.schema_name + ".global.localhost"
		domain.tenant = tenant 
		domain.is_primary = True
		domain.save()

		messages.success(request,'账户 {} 成功创建'.format(name))


		with schema_context(username):
			ac = Accounts(name=username, money=0).save()

		return redirect('home:login')
	return render(request,'login.html')
	
def login(request):
	if request.method=="POST":
		username = request.POST['username']
		password = request.POST['password']

		user = auth.authenticate(username=username,password=password)
		if user is not None:
			auth.login(request, user)
			messages.success(request,'{},  欢迎 :)'.format(user))
			# url = "http://" + username + ".global.localhost:8000/welcome/"
			# return redirect(url)
			# with connection.cursor() as cursor:
			# 	cursor.execute(f"SET search_path to " + username)
			#	cursor.execute(f"ALTER ROLE django_user SET search_path TO " + request.user.username + " ,public" )
			return redirect('inventory:dashboard')
		else:
			messages.error(request,'用户名或密码不正确')
		
	return render(request,'login.html')


def logoutUser(request):
	logout(request)
	return redirect('home:index')

@login_required(login_url='home:login')
def profile(request):
	form = UserForm(instance=request.user)
	if request.method == "POST":
		form = UserForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			messages.success(request, '{} 已修改'.format(request.user))
			return redirect('inventory:dashboard')
		else:
			messages.error(request, '{} 未修改'.format(request.user))
			messages.error(request, form.errors)
	header = "编辑 {}".format(request.user)
	return render(request, 'profile.html', {'form': form, 'header' : header })

@login_required(login_url='home:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, '你的密码已成功更新!')
            return redirect('inventory:dashboard')
        else:
            messages.error(request, '请更正以下错误')
            messages.error(request, form.errors) 
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })	
	

home/templates/change_password.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<div class="card-header py-3">
  <h4 class="m-0 font-weight-bold text-primary"> 修改密码 </h4>
</div>

<br>
<div class="container">
	<form method="post">
	  {% csrf_token %}

	  {% for field in form %}

			<div class="form-group row">
				<label for="id_{{field.name}}" class="col-2 col-form-label"> {{ field.label }}</label>
				<div class="col-10">
					<div class="col-4 offset-1">
						{{ field }}
					</div>
				</div>
	    </div>
	    {% endfor %}

	  <button class ="btn btn-primary">保存更改</button>
	  <input action="action" class="btn btn-link" onclick="window.history.go(-1); 
		return false;" type="submit" value="取消"/>
	</form>
</div>

{% endblock %}

home/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>锋行智慧工厂</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/img/favicon.ico' %} " />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%  static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="#page-top">锋行智慧工厂</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">关于</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">服务</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">特点</a></li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" 
                    href="{% url 'inventory:dashboard' %}">欢迎, {{ user.first_name }}
                  </a>
                </li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" 
                    href="{% url 'home:logoutUser' %}">注销</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:login' %}">登录</a>
                </li>
                {% endif %}

                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">联系我们</a></li>
                
            </ul>
          </div>
        </div>
      </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-white font-weight-bold">互联网的伟大之处，在于每个人都在分享自己的“芝士”</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">您的发展是我们的主要目标。有效地管理贵公司的数据和规划对您的发展至关重要。锋行智慧工厂管理系统是为您的需求而设计的。只要创建一个账户并开始使用它。</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">了解更多</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">我们有你需要的东西!</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">锋行智慧工厂通过有效和安全地管理你的公司数据来满足你的需求。它有助于做出增加库存的决定，我们以此来帮助你的发展。</p>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">开始吧!</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <h2 class="text-center mt-0">为您提供服务</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
                            <h3 class="h4 mb-2">安全性</h3>
                            <p class="text-muted mb-0">创建自己的账户，以高度的安全性管理你的数据</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
                            <h3 class="h4 mb-2">与时俱进</h3>
                            <p class="text-muted mb-0">你只需要更新你的详细资料就够了</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                            <h3 class="h4 mb-2">用户友好</h3>
                            <p class="text-muted mb-0">它很容易使用，任何人都可以轻松访问</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-heart text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Made with Love</h3>
                            <p class="text-muted mb-0">Is it really free to use if it's not made with love?</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/1.jpg' %}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">与客户有更好的沟通</div>
                                <div class="project-name">通过明确告知产品的可用性及其订单交付信息，迅速抓住客户的注意力</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/2.jpg' %}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">分析</div>
                                <div class="project-name">衡量你的公司发展如何，并开始改善它</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/3.jpg' %}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">隐私</div>
                                <div class="project-name">以高安全性管理你的公司数据</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/4.jpg' %}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">简单明了</div>
                                <div class="project-name">精心设计，易于使用，并获得清晰准确的信息，知道下一步该怎么做</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/5.jpg' %}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">减少成本</div>
                                <div class="project-name">管理你的订单和原材料，以便你能有效地减少公司的损失</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="portfolio-box">
                            <img class="img-fluid" src="{% static 'home/assets/img/portfolio/thumbnails/6.jpg' %}" alt="" />
                            <div class="portfolio-box-caption p-3">
                                <div class="project-category text-white-50">自动化</div>
                                <div class="project-name">完全自动化的功能。只需更新你的详细资料。你的数据会自动存储</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
        <section class="page-section bg-dark text-white">
            <div class="container text-center">
                <h2 class="mb-4">现在就开始发展你的业务</h2>
                <a class="btn btn-light btn-xl" href="{% url 'inventory:dashboard' %}">出发吧</a>
            </div>
        </section>
        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">保持联系</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">有任何疑问吗？请给我们打电话或发电子邮件，我们会尽快给你答复!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <a class="d-block" href="#">+86 17669499969</a>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block" href="#">geekjkfx@qq.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2022 - 锋行智慧工厂</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %} "></script>
    </body>
</html>

home/templates/profile.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

{% if header %}
<div class="card-header py-3">
  <h4 class="m-0 font-weight-bold text-primary"> {{ header }} </h4>
</div>
{% endif %}

   
<br>
<div class="container">
	<form method="POST">
		{% csrf_token %} 

		<div class="form-group row">
			<label for="id_{{field.name}}" class="col-2 col-form-label"> {{ form.first_name.label }}</label>
			<div class="col-10">
				<div class="col-4 offset-1">
					{{ form.first_name }}
				</div>
			</div>
    </div>

		<div class="form-group row">
			<label for="id_{{field.name}}" class="col-2 col-form-label"> {{ form.last_name.label }}</label>
			<div class="col-10">
				<div class="col-4 offset-1">
					{{ form.last_name }}
				</div>
			</div>
    </div>

		<div class="form-group row">
			<label for="id_{{field.name}}" class="col-2 col-form-label"> {{ form.email.label }}</label>
			<div class="col-10">
				<div class="col-4 offset-1">
					{{ form.email }}
				</div>
			</div>
    </div>

    <div class="button-group row">
    	<label class="col-2 col-form-label"> 密码 </label>
      <a href="{% url 'home:change_password' %}" class="btn btn-link" role="button">
      重置密码 </a>
		</div>

    <!--<input type="submit" name="Save">-->

    <br>
    <br>
    <button class ="btn btn-primary">保存</button>
   	<!--<button class="btn btn-link" onclick="javascript:history.back();">Save</button>-->
    <input action="action" class="btn btn-link" onclick="window.history.go(-1); 
    	return false;" type="submit" value="取消"/>
	</form>
</div>



{% endblock %}


<!-- This is common add html for all -->