IMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('inventory.urls')),
    path('', include('home.urls')),
]

inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("add_amount/", views.add_amount, name="add_amount"),
    path("add_transaction/", views.add_transaction, name="add_transaction"),
    path("view_credit/", views.view_credit, name="view_credit"),
    path("view_debit/", views.view_debit, name="view_debit"),
    path(
        "view_all_transaction/", views.view_all_transaction, name="view_all_transaction"
    ),
    # For Employee
    path("employee/", views.employee, name="employee"),
    path("add_employee/", views.add_employee, name="add_employee"),
    path("<int:emp_id>/emp_edit/", views.emp_edit, name="emp_edit"),
    path(
        "<int:emp_id>/delete_employee/", views.delete_employee, name="delete_employee"
    ),
    path("<int:emp_id>/view_works/", views.view_works, name="view_works"),
    path("<int:emp_id>/add_work/", views.add_work, name="add_work"),
    # For Salary
    path("<int:emp_id>/pay_now/", views.pay_now, name="pay_now"),
    path("salary_cal/", views.salary_cal, name="salary_cal"),
    path("pay_all/", views.pay_all, name="pay_all"),
    path("<int:emp_id>/salary_details/", views.salary_details, name="salary_details"),
    # For Customer
    path("customer/", views.customer, name="customer"),
    path("add_customer/", views.add_customer, name="add_customer"),
    path("<int:cus_id>/cust_edit/", views.cust_edit, name="cust_edit"),
    path(
        "<int:cus_id>/delete_customer/", views.delete_customer, name="delete_customer"
    ),
    # For orders
    path("order_all/", views.order_all, name="order_all"),
    path("order_not_delivered/", views.order_not_delivered, name="order_not_delivered"),
    path("order_delivered/", views.order_delivered, name="order_delivered"),
    path("<int:cus_id>/order_list/", views.order_list, name="order_list"),
    path("<int:cus_id>/order_now/", views.order_now, name="order_now"),
    path("<int:ord_id>/order_details/", views.order_details, name="order_details"),
    path("<int:ord_id>/delivered/", views.delivered, name="delivered"),
    # path('<int:ord_id>/download_order/', views.download_order, name='download_order'),
    # For product
    path("product_details/", views.product_details, name="product_details"),
    path("add_product/", views.add_product, name="add_product"),
    path("<int:pro_id>/edit_product/", views.edit_product, name="edit_product"),
    path("<int:pro_id>/delete_product/", views.delete_product, name="delete_product"),
    # For Supplier
    path("supplier/", views.supplier, name="supplier"),
    path("add_supplier/", views.add_supplier, name="add_supplier"),
    path("<int:sup_id>/sup_edit/", views.sup_edit, name="sup_edit"),
    path(
        "<int:sup_id>/delete_supplier/", views.delete_supplier, name="delete_supplier"
    ),
    # For Raw Materials
    path("materials/", views.materials, name="materials"),
    path("add_material/", views.add_material, name="add_material"),
    path("<int:mat_id>/material_edit/", views.material_edit, name="material_edit"),
    path(
        "<int:mat_id>/delete_material/", views.delete_material, name="delete_material"
    ),
    path("view_purchase/", views.view_purchase, name="view_purchase"),
    path("buy_material/", views.buy_material, name="buy_material"),
   #  员工考勤
    path("attendance/", views.attendance, name="attendance"),
    path("facerec/", views.facerec, name="facerec"),
]

inventory/views.py
from __future__ import unicode_literals
from cv2 import COLOR_RGB2BGR
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseNotFound
from django.template import loader
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.utils.timezone import now
from datetime import datetime, timedelta
from django.db.models import Q
from .models import *	
from .forms import *
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection
from django_tenants.utils import schema_context

# from reportlab.pdfgen import canvas
# from weasyprint import HTML
# from weasyprint.fonts import FontConfiguration
from django.template.loader import render_to_string

import threading
import cv2
import numpy as np
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image
from facenet_pytorch import MTCNN, InceptionResnetV1
import torch
from torch.utils.data import DataLoader
from torchvision import datasets
import numpy as np
import pandas as pd
import os
import cv2
from PIL import Image
import datetime
import os
from pathlib import Path

# Create your views here.
def get_profit(tr):
	res = 0 
	for t in tr:
		if t.type == 0 :
			res += t.amt 
	return res 			

def get_expenses(tr):
	res = 0 
	for t in tr:
		if t.type == 1 :
			res += t.amt 
	return res

@login_required(login_url='home:login')
def dashboard(request):
	with schema_context(request.user.username ):
		today 	= datetime.date.today()

		month = []
		for i in range(1, 13):
			tr 	= Transaction.objects.filter(date__month=i, date__year=today.year)	
			pro = get_profit(tr)
			exp = get_expenses(tr)
			month.append(int(pro-exp))

		tr = Transaction.objects.filter(date__month=today.month, date__year=today.year)
		income 	= get_profit(tr)
		expenses = get_expenses(tr)

		try:
			profit_percentage = int(((income-expenses) / expenses ) * 100)
		except ZeroDivisionError:
			profit_percentage = 100 

		dict = { 

			"initial" 	: get_object_or_404(Accounts, name=request.user.username) ,
			"income"   	: income ,
			"expenses"	: expenses ,
			"profit_percentage"	: profit_percentage , 
			"loss_percetage"	: 100 - profit_percentage ,  
		}

		return render(request, 'inventory/dashboard.html', { 'dict' : dict , 'trans' : tr , 'month' : month })



@login_required(login_url='home:login')
def add_amount(request):
	with schema_context(request.user.username ):
		ac = get_object_or_404(Accounts, name=request.user.username)
		if request.method == "POST":
			form = AccountForm(request.POST, instance=ac)
			if form.is_valid():
				form.save()
				messages.success(request, '账户更新')
				return redirect('inventory:dashboard')
			else:
				messages.error(request, '账户未更新')
				messages.error(request, form.errors)
		else:
			form = AccountForm(instance=ac)
		header = "初始账户余额"
		return render(request, 'inventory/add_common.html', {'form': form, 'header' : header })


# _____________________ For Transactions _______________________________

@login_required(login_url='home:login')
def view_credit(request):
	with schema_context(request.user.username ):
		tr 	   = Transaction.objects.filter(type=0)
		header = "入账交易详情"
		return render(request, 'inventory/transaction.html', { 'trans' : tr, "header" : header })


@login_required(login_url='home:login')
def view_debit(request):
	with schema_context(request.user.username ):
		tr 	   = Transaction.objects.filter(type=1)
		header = "出账交易详情"
		return render(request, 'inventory/transaction.html', { 'trans' : tr, "header" : header })

@login_required(login_url='home:login')
def view_all_transaction(request):
	with schema_context(request.user.username ):
		tr 	   = Transaction.objects.all()
		header = "所有交易详情"
		return render(request, 'inventory/transaction.html', { 'trans' : tr, "header" : header })

# Have to complete accounts 
@login_required(login_url='home:login')
def add_transaction(request):
	with schema_context(request.user.username ):
		form=TransactionForm(request.POST or None, request.FILES or None)
		if request.method=="POST":
			form=TransactionForm(request.POST)
			if form.is_valid():
				amt  = form.cleaned_data.get('amt')
				type = form.cleaned_data.get('type')
				des  = form.cleaned_data.get('description')
				ac 	 = get_object_or_404(Accounts, name=request.user.username)

				if type == 1 and ac.is_available(amt) == False :
					messages.error(request, '抱歉，账户余额不足')	
					messages.error(request, '{} 薪资未被更新'.format(emp))	
					return redirect('inventory:salary_cal')

				if type == 1 :
					ac.reduce_amt(amt)
				else:
					ac.increase_amt(amt)
				ac.save()

				form.save()
				messages.success(request, des )
				return redirect('inventory:dashboard')
			else:
				messages.error(request, '交易失败。')
				messages.error(request, form.errors)
		header = "新交易记录" 
		return render(request,'inventory/add_common.html',{'form': form, 'header' : header })


	
# _____________________ For Employee _______________________________

@login_required(login_url='home:login')
def employee(request):
	with schema_context(request.user.username ):
	#with connection.cursor() as cursor:
		#cursor.execute(f"SET search_path to " + )
		Emps = Employee.objects.all()
		return render(request, 'inventory/employee.html', { 'Emps': Emps })   
@login_required(login_url='home:login')
def add_employee(request):
	with schema_context(request.user.username ):
		form=EmployeeForm(request.POST or None, request.FILES or None)
		if request.method=="POST":
			form=EmployeeForm(request.POST)
			if form.is_valid():
				form.save()
				# os.mkdir("inventory/static/facerec/data/infer/"+)
				messages.success(request, '添加员工成功。')
				return redirect('inventory:employee')
			else:
				messages.error(request, '员工未被添加。')
				messages.error(request, form.errors)
		header = "在此创建员工" 
		return render(request,'inventory/add_common.html',{'form': form, 'header' : header })

		
@login_required(login_url='home:login')
def emp_edit(request, emp_id):
	with schema_context(request.user.username ):
		emp = get_object_or_404(Employee, pk=emp_id)
		if request.method == "POST":
			form = EmployeeForm(request.POST, instance=emp)
			if form.is_valid():
				form.save()
				messages.success(request, '{} 已更新'.format(emp.name))
				return redirect('inventory:employee')
			else:
				messages.error(request, '{} 未被更新'.format(emp.name))
				messages.error(request, form.errors)
		else:
			form = EmployeeForm(instance=emp)
		header = "{} 详情".format(emp)
		return render(request, 'inventory/add_common.html', {'form': form, 'header' : header })

@login_required(login_url='home:login')
def delete_employee(request, emp_id):
	with schema_context(request.user.username ):
		emp = get_object_or_404(Employee, pk=emp_id)
		messages.success(request, '{} 已被删除。'.format(emp))
		emp.delete()
		return redirect('inventory:employee')

@login_required(login_url='home:login')
def view_works(request, emp_id):
	with schema_context(request.user.username ):
		emp = get_object_or_404(Employee, pk=emp_id)
		wk = Work.objects.filter(emp=emp_id)
		return render(request, 'inventory/view_works.html', { 'wk' : wk, 'emp' : emp })

@login_required(login_url='home:login')
def add_work(request, emp_id):
	with schema_context(request.user.username ):
		emp = get_object_or_404(Employee, pk=emp_id)
		if request.method=="POST":
			form=WorkForm(request.POST)
			if form.is_valid():
				form = form.save(commit=False)
				form.emp = emp 
				if(form.material.is_available(form.weight)):
					form.product.add_product(form.weight)
					form.material.reduce(form.weight)
					try:
						raw_waste = Products.objects.get(name='raw_waste')
					except ObjectDoesNotExist:
						raw_waste = Products(name='raw_waste', cost=0, wages=0, weight=0)

					w = ( form.weight / form.material.getmake()) - form.weight 

					raw_waste.add_product(w)
					raw_waste.save()

					emp.add_bonus(form.product.get_wages() * form.weight)
					emp.save()
					form.save()
					messages.success(request, '{} 工作任务已更新'.format(emp))
					return view_works(request, emp_id)
				else:
					messages.error(request, '没有这么多的原材料来制造这种产品')
			messages.error(request, '{} 工作任务未被更新'.format(emp))

		header = "为 {} 添加工作任务".format(emp)
		form = WorkForm(initial={'emp': emp })
		return render(request, 'inventory/add_common.html', {'form' : form, 'header' : header })


# _____________________ For ProductS _______________________________

@login_required(login_url='home:login')
def product_details(request):
	with schema_context(request.user.username ):
		pro = Products.objects.all()
		return render(request, 'inventory/product_details.html', { 'pro': pro })	

@login_required(login_url='home:login')
def add_product(request):
	with schema_context(request.user.username ):
		form=ProductForm(request.POST or None, request.FILES or None)
		if request.method=="POST":
			form=ProductForm(request.POST)
			if form.is_valid():
				form.save()
				messages.success(request, '产品已被创建')
				return redirect('inventory:product_details')
			else:
				messages.error(request, '产品未被创建')
				messages.error(request, form.errors)
		header = '创建新产品'
		return render(request,'inventory/add_common.html',{'form': form, 'header' : header })

@login_required(login_url='home:login')
def edit_product(request, pro_id):
	with schema_context(request.user.username ):
		pro = get_object_or_404(Products, pk=pro_id)
		if request.method == "POST":
			form = ProductForm(request.POST, instance=pro)
			if form.is_valid():
				form.save()
				messages.success(request, '{} 已被更新'.format(pro))
				return redirect('inventory:product_details')
		else:
			form = ProductForm(instance=pro)
		header = "{} 详情".format(pro) 
		return render(request, 'inventory/add_common.html', {'form': form, 'header' : header })


@login_required(login_url='home:login')

inventory/templates/inventory/materials.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800">原材料详情</h1>
<p class="mb-4">查看所有存在的材料的细节和它们的可用性状态</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">原材料表</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>名称</th>
            <th>重量</th>
            <th>花费</th>
            <th>编辑</th>
            <th>删除</th>
          </tr>
        </thead>
        <tbody align="center">
          
          <ul>
        	{% for m in mat %}
              
        	<tr>
            
              <td>{{ m.id }} </td>
        	    <td>{{ m.name }} </td> 
        	    <td>{{ m.weight }} </td>
        	    <td>{{ m.cost }} </td>
              
              <!-- Update -->
              <td>
                  <a href="{% url 'inventory:material_edit' m.id %}" class="btn btn-info btn-circle btn-sm">
                    <i class="fas fa-info-circle"></i>
                  </a>  
              </td>

              <!-- delete -->
              <td>

                  <a class="btn btn-danger btn-circle btn-sm" href="{% url 'inventory:delete_material' m.id %}" 
                      data-toggle="modal" data-target="#{{ m }}">
                    <i class="fas fa-trash"></i>
                  </a>
                  <div class="modal fade" id="{{ m }}" tabindex="-1" role="dialog" 
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">你确定删除 {{ m }} 吗？</h5>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal"> 取消 </button>
                          <a class="btn btn-danger"  href="{% url 'inventory:delete_material' m.id %}"> 删除 </a>
                        </div>
                      </div>
                    </div>
                  </div>

              </td>
        	</tr>
        
    
        	{% endfor %}
        	</ul>
        </tbody>
      </table>
    </div>
  </div>
</div>

  


<!-- Add Customer -->  

<div class="button-group" align="right">
  <a href="{% url 'inventory:add_material' %}" class="btn btn-primary" role="button">
  添加原材料 </a>
  <a href="{% url 'inventory:buy_material' %}" class="btn btn-primary" role="button">
  购买原材料 </a>
</div>


{% endblock %}

inventory/templates/inventory/order.html
{% extends 'inventory/base.html' %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800">订单详情</h1>
<p class="mb-4">查看订单细节和交付状态</p> 

<a href="{% url 'inventory:order_all' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">查看所有客户订单</span>
</a>

<a href="{% url 'inventory:order_delivered' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">已交付的订单</span>
</a>

<a href="{% url 'inventory:order_not_delivered' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">未交付的订单</span>
</a>

<div class="card shadow mb-4"> 
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">客户订单记录</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th> ID </th>
              <th> 客户 </th>
              <th> 下单日期 </th>
              <th> 数量 </th>
              <th> 交付日期 </th>
              <th>详情</th>
            </tr>
          </thead>
          <tbody>
    		    <ul> 
      			  {% for o in order %} 
        				  <tr>
                    <td> {{ o.id }} </td>
                    <td> {{ o.cus }} </td>
                    <td> {{ o.Odate }} </td>
                    <td> {{ o.total_amt }} </td>
                    {% if o.isDelivered %}
                      <td> {{ o.Ddate }} </td>
                    {% else %}
                      <td>
                          <a href="{% url 'inventory:delivered' o.id %}" class="btn btn-success btn-icon-split">
                            <span class="icon text-white-50">
                              <i class="fas fa-check"></i>
                            </span>
                            <span class="text"> 立即送达 </span>
                          </a>
                      </td>
                    {% endif %}

                    <td> 
                          <a href="{% url 'inventory:order_details' o.id %}"> 详情 
                              <i class="fas fa-info-circle"></i> 
                          </a>
                     </td>

                 </tr> 
			        {% endfor %}
	         </ul>
          </tbody>
        </table>
      </div>
    </div>
</div>

{% endblock %}

inventory/templates/inventory/product_details.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800">产品详情</h1>
          <p class="mb-4">查看所有可用产品的详细信息</p>
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">产品表</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>名称</th>
                      <th>重量</th>
                      <th>每千克成本</th>
                      <th>每千克的工钱</th>
                      <th>修改</th>
                      <th>删除</th>
                    </tr>
                  </thead>
                  <tbody align="center">
                    
            <ul>
						{% for p in pro %}
						<tr>
              
                <td>{{ p.id     }} </td>
						    <td>{{ p.name   }} </td> 
						    <td>{{ p.weight }} </td>
						    <td>{{ p.cost   }} </td>
                <td>{{ p.wages  }} </td>
                
                <!-- Update -->
                <td>
                    <a href="{% url 'inventory:edit_product' p.id %}" class="btn btn-info btn-circle btn-sm">
                      <i class="fas fa-info-circle"></i>
                    </a>  
                </td>

                <!-- delete -->
                <td>

                  <a class="btn btn-danger btn-circle btn-sm" href="{% url 'inventory:delete_material' p.id %}" 
                      data-toggle="modal" data-target="#{{ p }}">
                    <i class="fas fa-trash"></i>
                  </a>
                  <div class="modal fade" id="{{ p }}" tabindex="-1" role="dialog" 
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel"> 你确定删除 {{ p }} 吗？</h5>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal"> 取消 </button>
                          <a class="btn btn-danger"  href="{% url 'inventory:delete_product' p.id %}"> 删除 </a>
                        </div>
                      </div>
                    </div>
                  </div>

              </td>
              
						</tr>
						{% endfor %}
						</ul>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

        <!-- Add Customer -->  

        <div class="button-group" align="right">
              <a href="{% url 'inventory:add_product' %}" class="btn btn-primary" role="button">
              添加产品 </a>
        </div>

      </div>

<!-- /.container-fluid -->

</div>


{% endblock %}

inventory/templates/inventory/supplier.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800">供应商详情</h1>
<p class="mb-4">查看所有供应商的详细资料</p>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">供应商表</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>ID</th>
                <th>名称</th>
                <th>地址</th>
                <th>手机号码</th>
                <th>编辑</th>
                <th>删除</th>
              </tr>
            </thead>
            <tbody align="center">
              
      <ul>
			{% for e in Sup %}
			<tr>
        
          <td>{{ e.id }} </td>
			    <td>{{ e.name }} </td> 
			    <td>{{ e.address }} </td>
			    <td>{{ e.phone }} </td>
          
          <!-- Update -->
          <td>
              <a href="{% url 'inventory:sup_edit' e.id %}" class="btn btn-info btn-circle btn-sm">
                <i class="fas fa-info-circle"></i>
              </a>  
          </td>

          <!-- delete -->
         <td>

            <a class="btn btn-danger btn-circle btn-sm" href="{% url 'inventory:delete_supplier' e.id %}" 
                data-toggle="modal" data-target="#{{ e }}">
              <i class="fas fa-trash"></i>
            </a>
            <div class="modal fade" id="{{ e }}" tabindex="-1" role="dialog" 
              aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">你确定删除 {{ e }} 吗？</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal"> 取消 </button>
                    <a class="btn btn-danger"  href="{% url 'inventory:delete_supplier' e.id %}"> 删除 </a>
                  </div>
                </div>
              </div>
            </div>
          
        </td>
			</tr>
			{% endfor %}
			</ul>
            </tbody>
          </table>
        </div>
      </div>
    </div>


  
  <!-- /.container-fluid -->

  <!-- Add Customer -->  

  <div class="button-group" align="right">
        <a href="{% url 'inventory:add_supplier' %}" class="btn btn-primary" role="button">
        添加供应商 </a>
  </div>



<!-- /.container-fluid -->




{% endblock %}

inventory/templates/inventory/transaction.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800"> {{ header }} </h1>

<a href="{% url 'inventory:view_all_transaction' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">所有交易记录</span>
</a>

<a href="{% url 'inventory:view_credit' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">入账记录</span>
</a>

<a href="{% url 'inventory:view_debit' %}" class="btn btn-light btn-icon-split">
  <span class="icon text-gray-600">
    <i class="fas fa-arrow-right"></i>
  </span>
  <span class="text">出账记录</span>
</a>



<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">交易记录表</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead align="center">
          <tr>
            <th> ID </th>
            <th> 描述 </th>
            <th> 数量 </th>
            <th> 日期 </th>
            <th> 类型 </th>
          </tr>
        </thead>
        <tbody align="center">
        	{% for tr in trans %}
        	<tr>  
              <td>{{ tr.id }} </td>
        	    <td>{{ tr.description }} </td> 
              <td>{{ tr.amt }}</td>
              <td>{{ tr.date }}</td>
              {% if tr.type %}
                <td> 出账 </td>
              {% else %}
                <td> 入账 </td>
              {% endif %}
          	</tr>
          	{% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>




<!-- Add Empplyeee -->  

<div class="button-group" align="right" >
  <a href="{% url 'inventory:add_transaction' %}" class="btn btn-primary" role="button" >
  添加交易记录 </a>
</div>

{% endblock %}

inventory/templates/inventory/view_purchase.html
{% extends 'inventory/base.html' %}

{% load static %}

{% block body %}

<h1 class="h3 mb-2 text-gray-800">原材料采购详情</h1>
<p class="mb-4">查看所有采购的原材料的细节</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">原材料表</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>ID</th>
            <th>From</th>
            <th>Material</th>
            <th>Cost</th>
            <th>Quantity</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody align="center">
          
          <ul>
        	{% for m in mat %}
              
        	<tr>       
              <td>{{ m.id }} </td>
              <td>{{ m.sup }} </td> 
              <td>{{ m.material }} </td> 
        	    <td>{{ m.total_amt }} </td>
        	    <td>{{ m.weight }} </td>
              <td>{{ m.date }} </td>
        	</tr>

        	{% endfor %}
        	</ul>
        </tbody>
      </table>
    </div>
  </div>
</div>

  


<!-- Add Customer -->  

<div class="button-group" align="right">
  <a href="{% url 'inventory:add_material' %}" class="btn btn-primary" role="button">
  Add New Materials </a>
  <a href="{% url 'inventory:buy_material' %}" class="btn btn-primary" role="button">
  Buy Materials </a>
</div>


{% endblock %}